# DEVELOPMENT ONLY, DO NOT USE FOR PRODUCTION
version: '3.5'

services: 
  cache:
    container_name: "uala-challenge-cache"
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=uala_challenge_2024
      - REDIS_PORT=6379
      - REDIS_DATABASES=1
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  api:
    container_name: "uala-challenge-api"
    build:
      context: ..
      dockerfile: ./docker/dockerfile
    image: pyegros/uala_challenge:latest
    ports:
      - "8080:8080"
    environment:
      CACHE_URL: "cache:6379"
      CACHE_PASSWORD: uala_challenge_2024
    depends_on:
      cache:
        condition: service_healthy